/* Atalaya · Personas y equipos · Perfil de identidad · Contenido
   Lectura complementaria y simbólica a partir de la fecha de nacimiento y del nombre completo.
   Doce arquetipos de identidad y nueve momentos de ciclo. No se muestran cifras ni el método: solo la lectura.
   Es orientativa: sirve para abrir conversación y autoconocimiento, nunca para decidir sobre una persona. */
(function () {
  const A = (window.Atalaya = window.Atalaya || {});
  const D = (A.identidadDatos = {});

  const T = (n, lema, disc, esencia, fortalezas, retos, trabajo, talento, motor, imagen, expresion, liderar, entorno, comunicar) => ({ n, lema, disc, esencia, fortalezas, retos, trabajo, talento, motor, imagen, expresion, liderar, entorno, comunicar });
  D.ARQ = {
    1: T('El Pionero', 'Abre camino', 'D',
      'Persona de iniciativa, que necesita ir por delante y dejar su sello. Piensa en «cómo empezarlo» antes que en «por qué no». Se crece cuando tiene autonomía y un reto claro.',
      ['Iniciativa y arranque', 'Decisión en momentos de duda', 'Independencia de criterio', 'Capacidad de abrir mercados o proyectos'],
      ['Impaciencia con los ritmos ajenos', 'Dificultad para delegar o pedir ayuda', 'Tendencia a imponer en lugar de convencer'],
      'Rinde en arranques, proyectos nuevos y situaciones que piden alguien que dé el primer paso. Le cuesta el mantenimiento rutinario.',
      'Arrancar lo que está parado y tomar decisiones cuando nadie se atreve.',
      'Por dentro le mueve la necesidad de ser dueño de su camino y de demostrar de lo que es capaz.',
      'Se le percibe seguro, directo y con determinación; a veces, distante o difícil de frenar.',
      'Se expresa con propuestas, iniciativas y resultados propios; aporta dirección.',
      'Darle objetivos y margen para decidir el cómo. Reconocer sus logros en público. Pactar pocos puntos de control y respetarlos.',
      'Proyectos con meta clara, autonomía y visibilidad.',
      'Directo, breve y orientado a la decisión.'),
    2: T('El Mediador', 'Une a las partes', 'S',
      'Persona sensible al clima y a las relaciones, que capta lo que otros no dicen. Busca acuerdo y cooperación, y trabaja mejor en pareja o en equipo que en solitario.',
      ['Diplomacia y tacto', 'Escucha y empatía', 'Detalle en lo relacional', 'Capacidad de sostener equipos'],
      ['Evitar el conflicto aunque haga falta', 'Dudar ante decisiones que dependen solo de ella', 'Sobrecargarse por no decir que no'],
      'Rinde en coordinación, atención a personas, negociación y equipos que necesitan cohesión. Le cuesta la confrontación abierta.',
      'Poner de acuerdo a personas distintas y detectar tensiones antes de que estallen.',
      'Por dentro le mueve la armonía, sentirse parte y ser útil a los demás.',
      'Se le percibe amable, prudente y accesible; a veces, poco firme.',
      'Se expresa acompañando, conectando y facilitando; aporta cohesión.',
      'Pedirle opinión en privado antes de las reuniones. Dar seguridad y reconocimiento sincero. Ayudarle a poner límites.',
      'Equipos estables, con buen trato y objetivos compartidos.',
      'Cercano, tranquilo y con tiempo para escuchar.'),
    3: T('El Comunicador', 'Da voz a las ideas', 'I',
      'Persona expresiva y creativa, que contagia entusiasmo y encuentra la forma de contar las cosas. Necesita variedad, contacto con gente y un espacio para crear.',
      ['Comunicación y persuasión', 'Creatividad', 'Optimismo que anima al equipo', 'Facilidad para presentar y vender ideas'],
      ['Dispersión entre muchos frentes', 'Dejar cosas a medias', 'Necesidad de aprobación'],
      'Rinde en ventas, comunicación, formación, marca y proyectos creativos. Le cuesta lo repetitivo y aislado.',
      'Explicar, convencer y dar vida a una idea.',
      'Por dentro le mueve expresarse, crear y sentirse reconocido por lo que aporta.',
      'Se le percibe simpático, brillante y social; a veces, poco constante.',
      'Se expresa con palabras, imágenes y relaciones; aporta energía y visibilidad.',
      'Darle variedad y escenario. Pactar pocos compromisos con fecha y revisarlos. Reconocer lo creativo y lo terminado.',
      'Ambientes dinámicos, con gente y libertad para proponer.',
      'Animado, visual y con ejemplos.'),
    4: T('El Constructor', 'Pone los cimientos', 'C',
      'Persona de método, constancia y palabra. Convierte las ideas en procesos que funcionan y necesita orden, claridad y tiempo para hacer las cosas bien.',
      ['Organización y método', 'Fiabilidad y constancia', 'Sentido práctico', 'Capacidad de sostener el esfuerzo'],
      ['Rigidez ante el cambio', 'Exceso de control o perfeccionismo', 'Dificultad para improvisar'],
      'Rinde en operaciones, administración, calidad, procesos y proyectos de largo recorrido. Le cuestan los cambios bruscos sin explicación.',
      'Ordenar lo que está desordenado y hacer que las cosas duren.',
      'Por dentro le mueve la seguridad, hacer un trabajo sólido y que se pueda confiar en ella.',
      'Se le percibe seria, responsable y estable; a veces, poco flexible.',
      'Se expresa con hechos, planes y procedimientos; aporta estructura.',
      'Explicar el porqué de los cambios con tiempo. Dar instrucciones claras y criterios de calidad. Reconocer la constancia.',
      'Tareas definidas, procesos claros y estabilidad.',
      'Ordenado, concreto y con datos.'),
    5: T('El Aventurero', 'Busca lo nuevo', 'I',
      'Persona inquieta, versátil y curiosa, que necesita movimiento y libertad. Se adapta rápido, aprende de la experiencia y se aburre con la rutina.',
      ['Adaptación al cambio', 'Versatilidad', 'Curiosidad y aprendizaje rápido', 'Capacidad de relación con perfiles muy distintos'],
      ['Inconstancia', 'Rechazo a normas y controles', 'Riesgo de dispersarse o de cambiar a menudo de rumbo'],
      'Rinde en ventas, desarrollo de negocio, proyectos variados, viajes y entornos cambiantes. Le cuesta lo burocrático.',
      'Moverse con soltura en lo incierto y encontrar oportunidades nuevas.',
      'Por dentro le mueve la libertad, la experiencia y no sentirse atado.',
      'Se le percibe dinámico, ingenioso y cercano; a veces, imprevisible.',
      'Se expresa probando, viajando y conectando; aporta adaptabilidad.',
      'Darle variedad y retos cambiantes. Pactar resultados, no horarios ni métodos. Revisar compromisos con frecuencia corta.',
      'Entornos con movimiento, novedad y autonomía.',
      'Ágil, sin rodeos y con margen para opinar.'),
    6: T('El Protector', 'Cuida de los suyos', 'S',
      'Persona responsable y entregada, que asume el cuidado del equipo y de la calidad. Necesita sentirse útil y que su entorno esté en armonía.',
      ['Responsabilidad y compromiso', 'Cuidado de las personas', 'Sentido de la justicia', 'Calidad en el servicio'],
      ['Cargar con más de lo que le toca', 'Dificultad para delegar', 'Implicarse demasiado en lo emocional'],
      'Rinde en atención al cliente, personas, calidad, servicio y coordinación de equipos. Le cuestan los entornos fríos o injustos.',
      'Hacerse cargo y conseguir que las personas se sientan atendidas.',
      'Por dentro le mueve ser necesario, cuidar y que las cosas estén bien hechas para los demás.',
      'Se le percibe fiable, cálido y protector; a veces, controlador.',
      'Se expresa cuidando, enseñando y responsabilizándose; aporta compromiso.',
      'Reconocer su entrega. Ayudarle a repartir la carga. Implicarle en decisiones que afectan a las personas.',
      'Equipos con buen ambiente y propósito de servicio.',
      'Cálido, respetuoso y con consideración por las personas.'),
    7: T('El Pensador', 'Va al fondo', 'C',
      'Persona reflexiva y analítica, que necesita entender antes de actuar. Profundiza, cuestiona y busca la verdad de las cosas. Trabaja bien con concentración y espacio propio.',
      ['Análisis y profundidad', 'Pensamiento crítico', 'Especialización', 'Intuición para detectar lo que no encaja'],
      ['Aislamiento', 'Desconfianza o exceso de escepticismo', 'Lentitud para decidir por querer más información'],
      'Rinde en análisis, investigación, finanzas, tecnología, calidad y puestos de especialista. Le cuestan las reuniones sin contenido y la improvisación.',
      'Encontrar la causa real de un problema y dar respuestas fundamentadas.',
      'Por dentro le mueve comprender, aprender y tener su propio espacio.',
      'Se le percibe reservado, sereno y competente; a veces, frío.',
      'Se expresa con análisis, preguntas y conocimiento; aporta criterio.',
      'Dar información completa y tiempo para pensar. Respetar su concentración. Pedirle su análisis por escrito.',
      'Trabajo con profundidad, autonomía y poco ruido.',
      'Preciso, argumentado y sin prisas.'),
    8: T('El Estratega', 'Gestiona y logra', 'D',
      'Persona orientada al logro, a la gestión de recursos y a los resultados tangibles. Piensa en grande, organiza y asume responsabilidades de peso.',
      ['Visión de negocio', 'Gestión de recursos y personas', 'Ambición y determinación', 'Resistencia bajo presión'],
      ['Exceso de control', 'Medir todo en resultados', 'Dureza en el trato cuando aprieta'],
      'Rinde en dirección, gestión, finanzas, ventas de alto valor y proyectos con objetivos ambiciosos. Le cuesta lo que no tiene impacto visible.',
      'Organizar recursos para conseguir resultados medibles.',
      'Por dentro le mueve el logro, la solidez y ser reconocido por lo que consigue.',
      'Se le percibe con autoridad, capaz y exigente.',
      'Se expresa con objetivos, cifras y decisiones; aporta capacidad de gestión.',
      'Darle responsabilidad real y objetivos ambiciosos. Hablar en resultados. Ayudarle a cuidar el clima del equipo.',
      'Retos de gestión, objetivos medibles y capacidad de decisión.',
      'Directo, con datos y orientado a resultados.'),
    9: T('El Humanista', 'Mira por todos', 'S',
      'Persona generosa y de mirada amplia, que piensa en el conjunto y en el sentido de lo que se hace. Sabe cerrar etapas y comprender puntos de vista distintos.',
      ['Visión de conjunto', 'Generosidad y tolerancia', 'Inspiración a partir de valores', 'Capacidad de cerrar y pasar página'],
      ['Idealismo poco práctico', 'Dificultad para poner límites', 'Dispersión en causas ajenas'],
      'Rinde en proyectos con propósito, formación, relaciones institucionales, responsabilidad social y cierre de proyectos. Le cuesta lo que choca con sus valores.',
      'Dar sentido al trabajo y comprender a personas muy distintas.',
      'Por dentro le mueve contribuir a algo mayor y que su trabajo tenga sentido.',
      'Se le percibe abierto, comprensivo y con mundo.',
      'Se expresa con valores, visión y ayuda; aporta sentido.',
      'Conectar sus tareas con el propósito. Pactar objetivos concretos y fechas. Reconocer su generosidad.',
      'Organizaciones con valores claros y proyectos con impacto.',
      'Inspirador, con el porqué y con respeto.'),
    11: T('El Inspirador', 'Ilumina el camino', 'I',
      'Persona muy intuitiva y sensible, con capacidad de inspirar a otros y de ver posibilidades antes que nadie. Vive con intensidad y necesita canalizar bien su energía.',
      ['Intuición', 'Capacidad de inspirar', 'Visión anticipada', 'Sensibilidad para las personas'],
      ['Tensión nerviosa e inseguridad', 'Idealismo', 'Altibajos de energía'],
      'Rinde en roles que piden visión, inspiración, formación, innovación y trato con personas. Le cuestan los entornos muy rígidos o fríos.',
      'Anticipar tendencias y motivar a otros con una visión.',
      'Por dentro le mueve inspirar, comprender y aportar algo que trascienda.',
      'Se le percibe especial, carismático y sensible.',
      'Se expresa con ideas que inspiran; aporta visión.',
      'Darle un propósito claro y espacio para proponer. Ayudarle a aterrizar las ideas en pasos. Cuidar su equilibrio.',
      'Proyectos con sentido, innovación y reconocimiento.',
      'Cercano, con el porqué y con confianza.'),
    22: T('El Arquitecto', 'Hace realidad lo grande', 'C',
      'Persona que une visión amplia y sentido práctico: imagina proyectos de gran alcance y sabe construirlos paso a paso. Necesita metas a la altura de su capacidad.',
      ['Visión con ejecución', 'Capacidad de construir a gran escala', 'Disciplina', 'Liderazgo práctico'],
      ['Autoexigencia muy alta', 'Presión por los resultados', 'Dificultad para delegar el detalle'],
      'Rinde en dirección de proyectos, expansión, ingeniería, operaciones y transformación. Le cuestan los objetivos pequeños o sin horizonte.',
      'Convertir una visión ambiciosa en una estructura que funciona.',
      'Por dentro le mueve dejar una obra sólida y útil para muchos.',
      'Se le percibe sólido, capaz y con ambición constructiva.',
      'Se expresa con proyectos y estructuras; aporta capacidad de realización.',
      'Darle proyectos de alcance con recursos y plazos realistas. Ayudarle a delegar. Reconocer el avance por fases.',
      'Proyectos ambiciosos con estructura y medios.',
      'Concreto, con visión y con plan.'),
    33: T('El Guía', 'Enseña y sostiene', 'S',
      'Persona con fuerte vocación de servicio y de enseñar, que sostiene a otros y transmite valores. Necesita sentir que su trabajo ayuda a crecer a las personas.',
      ['Vocación de servicio', 'Capacidad de enseñar', 'Compasión', 'Responsabilidad hacia el grupo'],
      ['Olvidarse de sí misma', 'Exceso de responsabilidad', 'Dificultad para decir que no'],
      'Rinde en formación, mentoría, personas, cuidado y liderazgo de equipos. Le cuestan los entornos competitivos sin sentido.',
      'Hacer crecer a otros y sostener al equipo en momentos difíciles.',
      'Por dentro le mueve servir, enseñar y ver crecer a los demás.',
      'Se le percibe protector, sabio y de confianza.',
      'Se expresa enseñando y acompañando; aporta crecimiento.',
      'Darle un papel de mentor. Proteger su tiempo. Reconocer su aportación al grupo.',
      'Equipos donde pueda formar y acompañar.',
      'Cálido, con sentido y respeto.')
  };

  /* Momento del ciclo personal (cambia cada año) */
  const M = (n, lema, texto, foco, evitar) => ({ n, lema, texto, foco, evitar });
  D.CICLO = {
    1: M('Etapa de inicio', 'Sembrar', 'Momento de empezar cosas nuevas, tomar la iniciativa y abrir proyectos.', 'Asignarle arranques, nuevos retos o un cambio de responsabilidad.', 'Tenerle en tareas de mantenimiento sin novedad.'),
    2: M('Etapa de alianzas', 'Cooperar', 'Momento de colaborar, tener paciencia y cuidar las relaciones; los resultados llegan más despacio.', 'Trabajo en equipo, alianzas, coordinación.', 'Presionarle por resultados rápidos en solitario.'),
    3: M('Etapa de expresión', 'Comunicar', 'Momento de creatividad, visibilidad y relaciones; buena época para presentar y comunicar.', 'Proyectos de comunicación, formación, presentaciones.', 'Aislarle o quitarle contacto con personas.'),
    4: M('Etapa de construcción', 'Consolidar', 'Momento de trabajo constante, orden y bases sólidas; pide disciplina.', 'Procesos, sistemas, organizar y documentar.', 'Cambiarle de prioridades cada semana.'),
    5: M('Etapa de cambio', 'Moverse', 'Momento de cambios, movimiento y nuevas experiencias; puede haber inquietud.', 'Proyectos variados, viajes, aprendizaje nuevo.', 'La rutina estricta sin margen.'),
    6: M('Etapa de responsabilidad', 'Cuidar', 'Momento centrado en responsabilidades, equipo y vida personal; pide equilibrio.', 'Coordinación de personas, calidad, servicio.', 'Sobrecargarle sin reconocer lo que sostiene.'),
    7: M('Etapa de reflexión', 'Profundizar', 'Momento de análisis, formación y replanteamiento; más hacia dentro que hacia fuera.', 'Formación, especialización, análisis y mejora.', 'Exigirle exposición constante o decisiones precipitadas.'),
    8: M('Etapa de logro', 'Cosechar', 'Momento de resultados, responsabilidad y reconocimiento; buena época para asumir más.', 'Objetivos ambiciosos, gestión, promoción.', 'Frenar su crecimiento sin explicación.'),
    9: M('Etapa de cierre', 'Cerrar', 'Momento de terminar etapas, soltar lo que ya no sirve y preparar lo siguiente.', 'Cerrar proyectos, traspasar conocimiento, revisar.', 'Empezar grandes proyectos nuevos de larga duración.')
  };

  D.ASPECTOS = {
    esencia: { t: 'Identidad de fondo', d: 'Quién es en lo esencial y qué viene a aportar.' },
    talento: { t: 'Talento natural', d: 'Lo que le sale solo, casi sin esfuerzo.' },
    motor: { t: 'Lo que le mueve por dentro', d: 'Su motivación más íntima.' },
    imagen: { t: 'Cómo le perciben', d: 'La primera impresión que causa.' },
    expresion: { t: 'Cómo se expresa y aporta', d: 'Su forma de hacer y de estar en el trabajo.' },
    ciclo: { t: 'Momento actual', d: 'La etapa personal que está viviendo este año.' }
  };

  D.AVISO = 'Lectura complementaria de carácter simbólico, a partir de la fecha de nacimiento y del nombre. No es una prueba validada: sirve para abrir conversación y para el autoconocimiento, nunca como criterio para seleccionar, promocionar, retribuir o despedir a nadie. Se usa con el consentimiento de la persona.';
})();
